defaults: &defaults
  event_name: 'Ruby Manor'
  main_site: 'http://rubymanor.org'
  main_slogan: 'Building <a href="http://rubymanor.org">Ruby Manor</a> as a community'
  event_description: |
    <p>Ruby Manor is a one-day, zero-bullshit fully-fledged conference about Ruby, the programming language.<p>
    <p>It&rsquo;s predicated on the belief that conferences don&rsquo;t need a lot of the ceremony and cruft that they&rsquo;ve acquired over the years. We don&rsquo;t need swag. We don&rsquo;t need fancy food. We just want to get together with like minded people and share ideas. We want to know <a href="/motivation">what motivates you</a>.</p>
    <p>Conferences aren&rsquo;t about buying a ticket and then forgetting about it, and turning up on the day expecting to be entertained. They&rsquo;re about engaging, participating, sharing ideas and challenging each other. Most of all, they&rsquo;re about what the community finds interesting, not about what the same old conference circuit speakers want to feed you.</p>
    <p>Visit <a href="http://rubymanor.org">the main site</a> for more information.</p>
  event_audience: |
    <p>Your audience will consist of people who are interested in coming to Ruby Manor: this mostly means Ruby programmers from London and the surrounding area, but there will also be many people who come from much further away.  There may be people who don&rsquo;t use Ruby, or aren&rsquo;t programmers, or both.  Primarily however, it&rsquo;s a Ruby-focussed and deeply-technical crowd.</p>
  proposals_topics: |
    <p>You may propose a talk about whatever you like.  Talks which are directly or indirectly about Ruby are always popular, but you are welcome to submit a proposal about whatever subject you think will be interesting to the audience.  If the audience are indeed interested, your proposal will be successful and you will get to give the talk on the day.  If they&rsquo;re not interested, your proposal will sink slowly and inexorably into oblivion and nobody will ever know the truth of what happened.  The <a href="rubymanor.org/#who">Ruby Manor team</a> will be actively <a href="#suggestions">leaving suggestions</a> on each talk proposal to help get the ball rolling.  However, if you&rsquo;re not quite sure your idea is ready for public feedback yet, or just want some reassurance that you&rsquo;re on the right track, <a href="mailto:guvner@rubymanor.org?subject=Can+I+get+some+help+coming+up+with+my+proposal%3F">please do get in touch with us</a> and we&rsquo;ll give you some pointers.</p>
  proposals_duration: |
    <p>Talks will be a maximum of 30 minutes + 10 minutes Q&A, but if you have something interesting that can be said in less time, that&rsquo;s great too. We&rsquo;ll build the schedule around the best proposals chosen by the community.</p>
  why_submit_a_proposal: |
    <p>It&rsquo;s a good opportunity to be heard by a large slice of the Ruby community, and we&rsquo;ll put together a high-quality video of your talk that you can share with everyone who couldn&rsquo;t get there on the day.</p>
  google_analytics:
    enabled: false
    account: ''
    domain: ''
    allow_linker: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  google_analytics:
    enabled: true
    account: 'UA-XXXXXX-X'
    domain: 'rubymanor.org'
    allow_linker: true